### ISSUE TITLE
Rename unprofessional-commentary.md to uncivil

### ISSUE THREAD

**Issue by chris-box** [ietf/Moderators#25]
The filename is the problem (https://github.com/ietf/Moderators/blob/main/unprofessional-commentary.md).
When renaming it, we need to also update links in the email templates that point to it.

**Comment by dhruvdhody** [comment]
I agree this can be closed without any change....

**Comment by chris-box** [comment]
Sorry Dhruv I don't understand you. I am proposing to make changes, i.e. renaming the file and updating template contents to match. I hope to do this over this week.

**Comment by dhruvdhody** [comment]
In the past we deemed it to be unnecessary as it only shows up in the file name/URL. It is not like unprofessional is a bad word that needs to be avoided...

And apologies I thought this was an old issue that you were just commenting on... If you feel that a change makes sense and adds clarity, please go ahead...

**Comment by chris-box** [comment]
Will do.
