### ISSUE TITLE
Immediate escalation

### ISSUE THREAD

**Issue by mnot** [ietf/Moderators#7]
It's not clear whether there are circumstances where the SAA can immediately escalate to level  1 or level 2. 

If someone says something so vile / obviously unprofessional that half of the list is wondering if there's going to be a response, it seems like it's a good candidate for immediate escalation.

**Comment by coopdanger** [comment]
Good point. I think having the discretion to jump to level 1 in the most egregious cases makes sense.

**Comment by dhruvdhody** [comment]
And/Or send a "To list" response even in Level 0 for most egregious cases so that the list is aware that some action is being taken?

**Comment by elear** [comment]
Jumping levels wills sometimes be appropriate, for sure.  I think having an example of when that is warranted should be given, thus to reduce surprise.

**Comment by coopdanger** [comment]
I added some text, see what you think.

**Comment by elear** [comment]
LGTM.

**Comment by mnot** [comment]
Seems fine, although the example you give seems more appropriate for an immediate ban, to me. Maybe give one or two more?

**Comment by coopdanger** [comment]
> Seems fine, although the example you give seems more appropriate for an immediate ban, to me. Maybe give one or two more?

We don't actually do bans. My sense is that in this community people value the opportunity to say "I was just joking" more than the ability to restrict posting rights in any way, which is why I made it a jump to level 1 only.

**Comment by martinthomson** [comment]
I have to say, that example is a little too inflammatory for me.  I would escalate that to the police, not level 1 (with appropriate caution regarding the risk of swatting).  Threats of bodily harm, credible or not, need a stronger response than this process can account for.

I would instead say particularly strong or obvious violations, such as direct "ad hominem" attacks (e.g., "you are a poor excuse for a human being", "your mother should have smothered you as an infant"), blatant disregard for decorum (e.g., repeated use of profanity), and other things should be able to skip the warning step. 

I would include a note about posting rights actions being the ultimate conclusion, but to point out that the SAA are definitely not in the decision path for that, though they might be in a position to recommend them more than other community members.

**Comment by elear** [comment]
Errr.  Yeah, Martin's right about the example.  I like one of the examples he gave, and they pleasantly remind me of "Ya Mama" by Wuf Ticket.

**Comment by dhruvdhody** [comment]
This can be closed now! We have text in the SOP for "Immediate escalation in egregious cases".
